### ISSUE TITLE
Dataset edge no-data funk single pixel buffer & large width striping (NYC)

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#33] opened 2017-07-20 18:42 UTC
There's always been funk along the coastlines, this issue is not about that. This is lower priority and not a ship block for v2.

Rather when we add in additional local sources over SRTM sometimes the new sources incorrectly show water bathymetry values as **0** instead of `no-data`. So at zoom 9 we'll see ETOPO bathy, and at zoom 10+ we'll instead see flat `0` elevations because the new source, say Norway, isn't setting it's no-data value right.

Can we fix this with a config, or will we need to add water mask logic?

**Examples:**

- NYC bathymetry doesn't look good, but neither did v1?! 😨 
    - http://localhost:4000/#13/40.7089/-74.0010
    - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/13/2412/3079.png
    - `ned13/USGS_NED_13_n41w074_IMG.tif, ned13/USGS_NED_13_n41w075_IMG.tif, srtm/N40W074.tif, srtm/N40W075.tif, gmted/30N090W_20101117_gmted_mea075.tif, gmted/30N150E_20101117_gmted_mea075.tif, gmted/30N180W_20101117_gmted_mea075.tif, etopo1/ETOPO1_Bed_g.tif`

Following up from: https://github.com/mojodna/marblecutter/issues/17.

**Comment by iandees** [comment] 2017-07-21 13:43
Off the southern tip of Manhattan it looks a little funny for sure:

([tile](https://terrain-lambda.dev.mapzen.com/normal/14/4823/6160.png); [around here](https://terrain-lambda.dev.mapzen.com/normal/preview#13/40.7089/-74.0010))
![image](https://user-images.githubusercontent.com/261584/28464920-13c8f6b8-6df5-11e7-85a7-54e4e88c3220.png)

([tile](https://terrain-lambda.dev.mapzen.com/normal/15/9647/12320.png); [around here](https://terrain-lambda.dev.mapzen.com/normal/preview#15/40.7088/-74.0064)
![image](https://user-images.githubusercontent.com/261584/28466024-eb2094ec-6df8-11e7-83a7-7b20b2186ecd.png)

Not sure what's going on there. But it seems to match up with what's going on in #31.

**Comment by iandees** [comment] 2017-07-21 13:53
One problem this uncovered was that the new footprint calculation sometimes generated empty geometries. There were 39 images from SRTM and NED that were entirely `nodata`, so the footprinting process ended up with an empty multipolygon geomtry in PostGIS. The second tile in the comment above pulled in a bunch of these empty geometries. I removed reference to those empty geometries from the database, but it didn't change the generated image.

```
footprints=> delete from footprints where st_isempty(wkb_geometry);
DELETE 38
```

**Comment by mojodna** [comment] 2017-07-21 16:40
> Rather when we add in additional local sources over SRTM sometimes the new sources incorrectly show water bathymetry values as 0 instead of no-data. So at zoom 9 we'll see ETOPO bathy, and at zoom 10+ we'll instead see flat 0 elevations because the new source, say Norway, isn't setting it's no-data value right.

I think it is setting the NODATA values correctly; it's that the source data has been produced such that water areas (which would have been NODATA) have been assigned `0` values. I don't think we can treat `0` as NODATA, because then we'd lose areas that are actually at sea level.

We could possibly post-process offending files (undoing the processing that they did) using something similar to `gdal_sieve.py` (but rather than filtering for small polygons, filter for large polygons with a specific value).

**Comment by mojodna** [comment] 2017-07-21 22:28
Noise fixed in 3985c17c31e23a8763cf0d3b4b4b8626290aa48c:

https://d34o1q5y1d9is8.cloudfront.net/normal/preview#15/40.7088/-74.0064

![image](https://user-images.githubusercontent.com/45/28484704-bffd0680-6e28-11e7-97b7-648bf9e0b129.png)

The root cause was that `RectBivariateSpline` was interpolating NODATA values (large negative numbers) with real values nearby, resulting in junk values. I took a first pass at implementing NODATA-aware spline interpolation using `SmoothBivariateSpline`, omitting coordinates w/ NODATA from its input. However, this proved to be rather (too) slow and still somewhat problematic.

Switching to `scipy.ndimage.zoom` allowed me to simplify, using cubic splines when no mask is present (producing the same output as the `RectBivariateSpline` version) and first-order splines when one is.

**Comment by nvkelso** [comment] 2017-07-21 23:28
Great work! Almost all the large black junk I was seeing before is removed now :)

Regarding the remaining stray pixels of black / rainbow in your tile image and in:

- http://d34o1q5y1d9is8.cloudfront.net/normal/13/2410/3080@2x.png
- sources: ned/ned19_n40x75_w074x25_nj_northeast_2007.tif, ned13/USGS_NED_13_n41w075_IMG.tif, srtm/N40W075.tif, etopo1/ETOPO1_Bed_g.tif

Do you think it would be better if we banned **srtm** from areas of **ned** coverage? (By modifying max_zoom of subset of **srtm** footprints?)

Maybe an algorithm that only tries to fill "large" holes with progressively worse alternative sources, else the worst source shows thru the "small" holes?

**Comment by mojodna** [comment] 2017-07-21 23:40
> Do you think it would be better if we banned srtm from areas of ned coverage? (By modifying max_zoom of subset of srtm footprints?)

Yes.

> Maybe an algorithm that only tries to fill "large" holes with progressively worse alternative sources, else the worst source shows thru the "small" holes?

Can you elaborate? Are you suggesting leaving the small holes open?

An alternative I've been gradually pondering (for aerial imagery) has been to blend edges somehow. It'd require some experimentation and probably isn't straightforward, but it would eliminate / smooth out what are effectively cliffs in places like this.

**Comment by nvkelso** [comment] 2017-07-21 23:56
_tl;dr_: **yes**

_Copying Slack conversation here:_

For the weird coastline no-data buffer stuff along coastline, I'm reminded of a technique that Tom Patterson and I used for Natural Earth raster where we buffered out "good" land values into the water a bit / assumed they were flat and then let other content thru past the larger buffer. would that be useful here?

The process was a little different in Photoshop now 10 years ago, but if you buffer out the data values, clip to original tile extent, intersect the data-buffer and the no-data buffer, and fill that area with it's nearest neighbors data values.

http://www.shadedrelief.com/shelton/e.html

Under section **Tip 4: Shoreline buffering**:

![pasted image at 2017_07_21 03_18 pm](https://user-images.githubusercontent.com/853051/28486268-7288434e-6e35-11e7-8c6c-682ef2a5696c.png)

1. To start, open your land cover image in RGB or CMYK color mode and double check that Photoshop is set to use nearest neighbor interpolation (Preferences/General/Image Interpolation).
2. Select and delete all water pixels so they are now transparent (Figure 20, upper left).
3. Duplicate the land cover layer.
4. Select the Move tool in the Tool palette. Then on the keyboard press the up arrow cursor once. The image will move up one pixel.
5. Merge the copied layer with original below.
6. Duplicate the merged layer and repeat steps 4 and 5. But this time nudge the copied layer to the right.
7. Repeat this process two more times, nudging the copied layer down and then to the left respectively.

Maybe another way to think about it is to use a lower rez version of the same high rez data between the high rez and the other sources? (Or we just have to make / use a water mask)

**Comment by nvkelso** [comment] 2017-07-21 23:57
> Can you elaborate? Are you suggesting leaving the small holes open?

No no-data holes, fill them with either `0` elevation value or blended values from neighboring pixels (either single source or multiple source pixel blend edges).

**Comment by nvkelso** [comment] 2017-07-22 00:24
(At some point we should split off remaining bad input sources for Norway, Canada versus the fixes in this issue for NYC.)

**Comment by nvkelso** [comment] 2017-07-25 18:21
Split off bathymetry no-data and 0 values into https://github.com/mojodna/marblecutter/issues/41, updated title and issue description.

**Closed** 2017-07-30 03:11 UTC
